apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myrabbitmq
  template:
    metadata:
      labels:
        app: myrabbitmq
    spec:
      containers:
        - name: myrabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
              name: myrabbitmq
            - containerPort: 15672
              name: myrabbitmq-mgmt

---
apiVersion: v1
kind: Service
metadata:
  name: myrabbitmq-service
spec:
  selector:
    app: myrabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: myrabbitmq
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: myrabbitmq-mgmt