version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - mymongodb
    networks:
      - default

  mymongodb:
    image: mongo:latest
    container_name: mymongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - default

#  myrabbitmq:
#    image: rabbitmq:3-management
#    container_name: myrabbitmq
#    restart: always
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    ports:
#      - "5672:5672"
#      - "15672:15672"

volumes:
  mongo_data:

networks:
  default:
    name: reto_epa_reactive_default
    driver: bridge